LineProfile : avoid NoneType error.
After having computed intensity profile, if output table is set to None,
an 'AttributeError: 'NoneType' object has no attribute 'GetTable'' is
raised.

Check if getArrayFromTable::outputTable is None.